name: CI
on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout latest version
        uses: actions/checkout@v2

      - name: install docfx
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install docfx --force

      - name: execute docfx to compile site
        run: |
          docfx

      - name: commit compiled site
        if: success()
        run: |
          git config user.name "Github actions"
          git config user.email builder@wearefreemarket.com
          git add ./_site --force
          git commit --message "compiled site update"  

      - name: push compiled site
        if: success()
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
