# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout latest version
        uses: actions/checkout@v2

      - name: install docfx
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install docfx --force

      - name: execute docfx
        run: docfx

      - uses: actions/upload-artifact@v2
        if: success()
        with: 
          name: docfx output
          path: _site/
